version: 0.0
os: linux
files:
  - source: build/libs/rest-service-0.0.1-SNAPSHOT.jar
    destination: /var/rest-service-app
  - source: scripts/stop_server.sh
    destination: /var/rest-service-app
  - source: scripts/start_server.sh
    destination: /var/rest-service-app
  - source: scripts/fix_previleges.sh
    destination: /var/rest-service-app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
