version: 0.0
os: linux
files:
  - source: rest-service-0.0.1-SNAPSHOT.jar
    destination: /var/rest-service-app
hooks:
  AfterInstall:
  - location: fix_previleges.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: start_server.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
    runas: root
